### ISSUE TITLE
Still some speling errors on the Dutch parachute page

### ISSUE THREAD

**Issue by axello** [tanyafish/parachute#5]
See blue marks on all pages.
Texts in raw_translations is good.

[Het_Parachute_Bericht_NL-2.pdf](https://github.com/tanyafish/parachute/files/6079118/Het_Parachute_Bericht_NL-2.pdf)

**Comment by tanyafish** [comment]
Updated as per image. If there are any further ones, please note which page rather than sending a new pdf, it's quicker.
